export enum Especialidade {
  CARDIOLOGISTA = "CARDIOLOGISTA",
  CLINICO_GERAL = "CLINICO GERAL",
  NUTRICIONISTA = "NUTRICIONISTA",
  ORTOPEDISTA = "ORTOPEDISTA",
  NEUROLOGISTA = "NEUROLOGISTA",
  GINECOLOGISTA = "GINECOLOGISTA",
  PEDIATRIA = "PEDIATRIA",
  PSICOLOGIA = "PSICOLOGIA",
  UROLOGISTA = "UROLOGISTA",
  REUMATOLOGISTA = "REUMATOLOGISTA",
  OFTALMOLOGISTA = "OFTALMOLOGISTA",
  OTORRINOLARINGOLOGISTA = "OTORRINOLARINGOLOGISTA"
}
